# -*- coding: utf-8 -*-

from django.db import models


class Clients(models.Model):
    id_cli = models.AutoField(db_column='ID_CLI', primary_key=True)
    idclient = models.CharField(db_column='IDCLIENT', unique=True, max_length=50)
    description = models.CharField(db_column='DESCRIPTION', max_length=100)
    inscriptiondate = models.DateTimeField(db_column='INSCRIPTIONDATE', blank=True, null=True)
    retiredate = models.DateTimeField(db_column='RETIREDATE', blank=True, null=True)
    tensionlevel = models.SmallIntegerField(db_column='TENSIONLEVEL', blank=True, null=True)
    firstname = models.CharField(db_column='FIRSTNAME', max_length=50, blank=True, null=True)
    lastname = models.CharField(db_column='LASTNAME', max_length=50, blank=True, null=True)
    address = models.CharField(db_column='ADDRESS', max_length=40, blank=True, null=True)
    phone1 = models.CharField(db_column='PHONE1', max_length=30, blank=True, null=True)
    phone2 = models.CharField(db_column='PHONE2', max_length=30, blank=True, null=True)
    fax = models.CharField(db_column='FAX', max_length=30, blank=True, null=True)
    taxid = models.CharField(db_column='TAXID', max_length=15, blank=True, null=True)
    city = models.CharField(db_column='CITY', max_length=30, blank=True, null=True)
    state = models.CharField(db_column='STATE', max_length=30, blank=True, null=True)
    zipcode = models.CharField(db_column='ZIPCODE', max_length=10, blank=True, null=True)
    email = models.CharField(db_column='EMAIL', max_length=254, blank=True, null=True)
    webpage = models.CharField(db_column='WEBPAGE', max_length=254, blank=True, null=True)
    user_defined1 = models.CharField(db_column='USER_DEFINED1', max_length=100, blank=True, null=True)
    user_defined2 = models.CharField(db_column='USER_DEFINED2', max_length=100, blank=True, null=True)
    user_defined3 = models.CharField(db_column='USER_DEFINED3', max_length=100, blank=True, null=True)
    user_defined4 = models.CharField(db_column='USER_DEFINED4', max_length=100, blank=True, null=True)
    user_defined5 = models.CharField(db_column='USER_DEFINED5', max_length=100, blank=True, null=True)
    user_defined6 = models.CharField(db_column='USER_DEFINED6', max_length=100, blank=True, null=True)
    user_defined7 = models.CharField(db_column='USER_DEFINED7', max_length=100, blank=True, null=True)
    user_defined8 = models.CharField(db_column='USER_DEFINED8', max_length=100, blank=True, null=True)
    user_defined9 = models.CharField(db_column='USER_DEFINED9', max_length=100, blank=True, null=True)
    user_defined10 = models.CharField(db_column='USER_DEFINED10', max_length=100, blank=True, null=True)
    user_defined11 = models.CharField(db_column='USER_DEFINED11', max_length=100, blank=True, null=True)
    user_defined12 = models.CharField(db_column='USER_DEFINED12', max_length=100, blank=True, null=True)
    user_defined13 = models.CharField(db_column='USER_DEFINED13', max_length=100, blank=True, null=True)
    user_defined14 = models.CharField(db_column='USER_DEFINED14', max_length=100, blank=True, null=True)
    user_defined15 = models.CharField(db_column='USER_DEFINED15', max_length=100, blank=True, null=True)
    user_defined16 = models.CharField(db_column='USER_DEFINED16', max_length=100, blank=True, null=True)
    user_defined17 = models.CharField(db_column='USER_DEFINED17', max_length=100, blank=True, null=True)
    user_defined18 = models.CharField(db_column='USER_DEFINED18', max_length=100, blank=True, null=True)
    user_defined19 = models.CharField(db_column='USER_DEFINED19', max_length=100, blank=True, null=True)
    user_defined20 = models.CharField(db_column='USER_DEFINED20', max_length=100, blank=True, null=True)
    user_defined21 = models.CharField(db_column='USER_DEFINED21', max_length=100, blank=True, null=True)
    user_defined22 = models.CharField(db_column='USER_DEFINED22', max_length=100, blank=True, null=True)
    user_defined23 = models.CharField(db_column='USER_DEFINED23', max_length=100, blank=True, null=True)
    user_defined24 = models.CharField(db_column='USER_DEFINED24', max_length=100, blank=True, null=True)
    user_defined25 = models.CharField(db_column='USER_DEFINED25', max_length=100, blank=True, null=True)
    user_defined26 = models.CharField(db_column='USER_DEFINED26', max_length=100, blank=True, null=True)
    user_defined27 = models.CharField(db_column='USER_DEFINED27', max_length=100, blank=True, null=True)
    user_defined28 = models.CharField(db_column='USER_DEFINED28', max_length=100, blank=True, null=True)
    user_defined29 = models.CharField(db_column='USER_DEFINED29', max_length=100, blank=True, null=True)
    user_defined30 = models.CharField(db_column='USER_DEFINED30', max_length=100, blank=True, null=True)
    user_defined31 = models.CharField(db_column='USER_DEFINED31', max_length=100, blank=True, null=True)
    user_defined32 = models.CharField(db_column='USER_DEFINED32', max_length=100, blank=True, null=True)
    user_defined33 = models.CharField(db_column='USER_DEFINED33', max_length=100, blank=True, null=True)
    user_defined34 = models.CharField(db_column='USER_DEFINED34', max_length=100, blank=True, null=True)
    user_defined35 = models.CharField(db_column='USER_DEFINED35', max_length=100, blank=True, null=True)
    user_defined36 = models.CharField(db_column='USER_DEFINED36', max_length=100, blank=True, null=True)
    user_defined37 = models.CharField(db_column='USER_DEFINED37', max_length=100, blank=True, null=True)
    user_defined38 = models.CharField(db_column='USER_DEFINED38', max_length=100, blank=True, null=True)
    user_defined39 = models.CharField(db_column='USER_DEFINED39', max_length=100, blank=True, null=True)
    user_defined40 = models.CharField(db_column='USER_DEFINED40', max_length=100, blank=True, null=True)
    user_defined41 = models.CharField(db_column='USER_DEFINED41', max_length=100, blank=True, null=True)
    user_defined42 = models.CharField(db_column='USER_DEFINED42', max_length=100, blank=True, null=True)
    user_defined43 = models.CharField(db_column='USER_DEFINED43', max_length=100, blank=True, null=True)
    user_defined44 = models.CharField(db_column='USER_DEFINED44', max_length=100, blank=True, null=True)
    user_defined45 = models.CharField(db_column='USER_DEFINED45', max_length=100, blank=True, null=True)
    user_defined46 = models.CharField(db_column='USER_DEFINED46', max_length=100, blank=True, null=True)
    user_defined47 = models.CharField(db_column='USER_DEFINED47', max_length=100, blank=True, null=True)
    user_defined48 = models.CharField(db_column='USER_DEFINED48', max_length=100, blank=True, null=True)
    user_defined49 = models.CharField(db_column='USER_DEFINED49', max_length=100, blank=True, null=True)
    user_defined50 = models.CharField(db_column='USER_DEFINED50', max_length=100, blank=True, null=True)
    user_defined51 = models.CharField(db_column='USER_DEFINED51', max_length=100, blank=True, null=True)
    user_defined52 = models.CharField(db_column='USER_DEFINED52', max_length=100, blank=True, null=True)
    user_defined53 = models.CharField(db_column='USER_DEFINED53', max_length=100, blank=True, null=True)
    user_defined54 = models.CharField(db_column='USER_DEFINED54', max_length=100, blank=True, null=True)
    user_defined55 = models.CharField(db_column='USER_DEFINED55', max_length=100, blank=True, null=True)
    user_defined56 = models.CharField(db_column='USER_DEFINED56', max_length=100, blank=True, null=True)
    user_defined57 = models.CharField(db_column='USER_DEFINED57', max_length=100, blank=True, null=True)
    user_defined58 = models.CharField(db_column='USER_DEFINED58', max_length=100, blank=True, null=True)
    user_defined59 = models.CharField(db_column='USER_DEFINED59', max_length=100, blank=True, null=True)
    user_defined60 = models.CharField(db_column='USER_DEFINED60', max_length=100, blank=True, null=True)
    user_defined61 = models.CharField(db_column='USER_DEFINED61', max_length=100, blank=True, null=True)
    user_defined62 = models.CharField(db_column='USER_DEFINED62', max_length=100, blank=True, null=True)
    user_defined63 = models.CharField(db_column='USER_DEFINED63', max_length=100, blank=True, null=True)
    user_defined64 = models.CharField(db_column='USER_DEFINED64', max_length=100, blank=True, null=True)
    user_defined65 = models.CharField(db_column='USER_DEFINED65', max_length=100, blank=True, null=True)
    user_defined66 = models.CharField(db_column='USER_DEFINED66', max_length=100, blank=True, null=True)
    user_defined67 = models.CharField(db_column='USER_DEFINED67', max_length=100, blank=True, null=True)
    user_defined68 = models.CharField(db_column='USER_DEFINED68', max_length=100, blank=True, null=True)
    user_defined69 = models.CharField(db_column='USER_DEFINED69', max_length=100, blank=True, null=True)
    user_defined70 = models.CharField(db_column='USER_DEFINED70', max_length=100, blank=True, null=True)
    user_defined71 = models.CharField(db_column='USER_DEFINED71', max_length=100, blank=True, null=True)
    user_defined72 = models.CharField(db_column='USER_DEFINED72', max_length=100, blank=True, null=True)
    user_defined73 = models.CharField(db_column='USER_DEFINED73', max_length=100, blank=True, null=True)
    user_defined74 = models.CharField(db_column='USER_DEFINED74', max_length=100, blank=True, null=True)
    user_defined75 = models.CharField(db_column='USER_DEFINED75', max_length=100, blank=True, null=True)
    user_defined76 = models.CharField(db_column='USER_DEFINED76', max_length=100, blank=True, null=True)
    user_defined77 = models.CharField(db_column='USER_DEFINED77', max_length=100, blank=True, null=True)
    user_defined78 = models.CharField(db_column='USER_DEFINED78', max_length=100, blank=True, null=True)
    user_defined79 = models.CharField(db_column='USER_DEFINED79', max_length=100, blank=True, null=True)
    user_defined80 = models.CharField(db_column='USER_DEFINED80', max_length=100, blank=True, null=True)
    user_defined81 = models.CharField(db_column='USER_DEFINED81', max_length=100, blank=True, null=True)
    user_defined82 = models.CharField(db_column='USER_DEFINED82', max_length=100, blank=True, null=True)
    user_defined83 = models.CharField(db_column='USER_DEFINED83', max_length=100, blank=True, null=True)
    user_defined84 = models.CharField(db_column='USER_DEFINED84', max_length=100, blank=True, null=True)
    user_defined85 = models.CharField(db_column='USER_DEFINED85', max_length=100, blank=True, null=True)
    user_defined86 = models.CharField(db_column='USER_DEFINED86', max_length=100, blank=True, null=True)
    user_defined87 = models.CharField(db_column='USER_DEFINED87', max_length=100, blank=True, null=True)
    user_defined88 = models.CharField(db_column='USER_DEFINED88', max_length=100, blank=True, null=True)
    user_defined89 = models.CharField(db_column='USER_DEFINED89', max_length=100, blank=True, null=True)
    user_defined90 = models.CharField(db_column='USER_DEFINED90', max_length=100, blank=True, null=True)
    user_defined91 = models.CharField(db_column='USER_DEFINED91', max_length=100, blank=True, null=True)
    user_defined92 = models.CharField(db_column='USER_DEFINED92', max_length=100, blank=True, null=True)
    user_defined93 = models.CharField(db_column='USER_DEFINED93', max_length=100, blank=True, null=True)
    user_defined94 = models.CharField(db_column='USER_DEFINED94', max_length=100, blank=True, null=True)
    user_defined95 = models.CharField(db_column='USER_DEFINED95', max_length=100, blank=True, null=True)
    user_defined96 = models.CharField(db_column='USER_DEFINED96', max_length=100, blank=True, null=True)
    user_defined97 = models.CharField(db_column='USER_DEFINED97', max_length=100, blank=True, null=True)
    user_defined98 = models.CharField(db_column='USER_DEFINED98', max_length=100, blank=True, null=True)
    user_defined99 = models.CharField(db_column='USER_DEFINED99', max_length=100, blank=True, null=True)
    user_defined100 = models.CharField(db_column='USER_DEFINED100', max_length=100, blank=True, null=True)
    insert_datetime = models.DateTimeField(db_column='INSERT_DATETIME', blank=True, null=True)
    update_datetime = models.DateTimeField(db_column='UPDATE_DATETIME', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'CLIENTS'
